version: "2"
services:
    mongo:
        image: mongo:4.4.1
        restart: always
        command: --configExpand rest
        ports:
            - 27017:27017
        logging:
            driver: none
    hub:
        image: ghcr.io/ajgherardi/hub:latest
        restart: always
        hostname: "hub"
        ports:
            - 8080:8080
            - 5353:5353
        volumes:
            - home-data:/app
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
        network_mode: "host"
        devices:
            - "/dev/bus/usb:/dev/bus/usb"
        depends_on:
            - mongo
    node-red:
        image: ghcr.io/ajgherardi/node-red:latest
        restart: always
        ports:
            - "1880:1880"
        volumes:
            - node-red-data:/data
        depends_on:
            - hub
volumes:
    node-red-data:
    home-data:
